"""error-fixes

Revision ID: 40349126cfe2
Revises: e963c35d0b61
Create Date: 2025-03-05 07:46:42.400136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '40349126cfe2'
down_revision = 'e963c35d0b61'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###