"""certifications

Revision ID: 5f1a023fc3f4
Revises: 723eaee4daf2
Create Date: 2025-03-04 22:05:31.207650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '5f1a023fc3f4'
down_revision = '723eaee4daf2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###