"""onboarding and off boarding

Revision ID: 6a79ad19edb1
Revises: 5f1a023fc3f4
Create Date: 2025-03-04 22:15:47.069528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '6a79ad19edb1'
down_revision = '5f1a023fc3f4'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###