"""add_performance_management

Revision ID: 853f55651f2c
Revises: 770d6e184844
Create Date: 2025-03-04 22:41:05.118888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '853f55651f2c'
down_revision = '770d6e184844'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###