"""add_leave_type_relationship

Revision ID: a23459bde3ee
Revises: 02cbc56ba993
Create Date: 2025-03-04 21:10:52.304466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = 'a23459bde3ee'
down_revision = '02cbc56ba993'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaves', sa.Column('leave_type_id', sa.String(length=36), nullable=False))
    op.create_foreign_key(None, 'leaves', 'leave_types', ['leave_type_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leaves', type_='foreignkey')
    op.drop_column('leaves', 'leave_type_id')
    # ### end Alembic commands ###