"""add_salary_tables

Revision ID: a5e863f2a0c1
Revises: a23459bde3ee
Create Date: 2025-03-04 21:38:09.412898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = 'a5e863f2a0c1'
down_revision = 'a23459bde3ee'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payslips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('basic_salary', sa.Float(), nullable=False),
    sa.Column('allowances', sa.Float(), nullable=True),
    sa.Column('deductions', sa.Float(), nullable=True),
    sa.Column('gross_salary', sa.Float(), nullable=False),
    sa.Column('net_salary', sa.Float(), nullable=False),
    sa.Column('tax_deducted', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payslips_id'), 'payslips', ['id'], unique=False)
    op.create_table('salaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('basic_salary', sa.Float(), nullable=False),
    sa.Column('allowances', sa.Float(), nullable=True),
    sa.Column('deductions', sa.Float(), nullable=True),
    sa.Column('gross_salary', sa.Float(), nullable=False),
    sa.Column('net_salary', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salaries_id'), 'salaries', ['id'], unique=False)
    op.create_table('tax_info',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('tax_regime', sa.String(length=20), nullable=True),
    sa.Column('tax_declarations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_tax_info_id'), 'tax_info', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_info_id'), table_name='tax_info')
    op.drop_table('tax_info')
    op.drop_index(op.f('ix_salaries_id'), table_name='salaries')
    op.drop_table('salaries')
    op.drop_index(op.f('ix_payslips_id'), table_name='payslips')
    op.drop_table('payslips')
    # ### end Alembic commands ###